# Configuration for Release Drafter
# This file should be in .github/release-drafter.yml

template: |
  ## What's Changed
  
  $CHANGES

categories:
  - title: "🚀 New Features"
    labels: ["enhancement", "feature"]
  - title: "🐛 Bug Fixes"
    labels: ["bug", "fix"]
  - title: "📚 Documentation"
    labels: ["documentation"]
  - title: "🏗️ Infrastructure"
    labels: ["ci", "dependencies"]
  - title: "📦 Dependencies"
    labels: ["dependencies"]

exclude-labels:
  - "skip-changelog"
  - "wip"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"