name: Autograde
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Run tests
        run: npm test
