name: Mark Stale Issues
# description: Automatically mark and close stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been inactive for 30 days. It will be closed in 7 days if no activity occurs."
          stale-pr-message: "This pull request has been inactive for 30 days. It will be closed in 7 days if no activity occurs."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: "pinned,security,help-wanted"
          exempt-pr-labels: "pinned,security,WIP"
          operations-per-run: 100
